version: '3.8'

services:
  bootstrap-node:
    build: .
    image: my-no-sql
    networks:
      - my_network
    container_name: bootstrap-node
    ports:
      - "8081:8080"
    environment:
      - NODE_TYPE=BOOTSTRAP
      - CONTAINER_NAME=bootstrap-node
    volumes:
      - my-nosql-db-data:/app/data

  node-1:
    image: my-no-sql
    networks:
      - my_network
    container_name: node-1
    ports:
      - "8082:8080"
    environment:
      - NODE_TYPE=NODE
      - BOOTSTRAP_NODE_HOST=bootstrap-node
      - BOOTSTRAP_NODE_PORT=8080
      - CONTAINER_NAME=node-1
    volumes:
      - my-nosql-db-data:/app/data

  node-2:
    image: my-no-sql
    networks:
      - my_network
    container_name: node-2
    ports:
      - "8083:8080"
    environment:
      - NODE_TYPE=NODE
      - BOOTSTRAP_NODE_HOST=bootstrap-node
      - BOOTSTRAP_NODE_PORT=8080
      - CONTAINER_NAME=node-2
    volumes:
      - my-nosql-db-data:/app/data

networks:
  my_network:
    driver: bridge

volumes:
  my-nosql-db-data:

